"""
Django settings for catching project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'acah2mj(qz(9fl7^d@+jvr&2&lcwx$dp#0q0au_w#yy@ljvmuv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'compressor',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'twitter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'catching.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'catching.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',)
}

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# Twitter Settings
# TWITTER_CONSUMER_KEY = '6twMuXytUoQJbYwndHKM26GSy'
# TWITTER_CONSUMER_SECRET = 'W0Wc52KEsSYV4paDFPwjLryZOMVJuDUvNgNW0nPohU36H63DZU'
# TWITTER_ACCESS_TOKEN = '728629981904023553-G2r1hGQlvZI1rGCT8bCOkigexaz9zz9'
# TWITTER_TOKEN_SECRET = 'dUih9U0ORHVJYhoHTROjmoGa6DUsaUcGSgqx5ZpBtKxwz'

# TWITTER_HASH_TAG = '#djangocon'
# TWITTER_FOLLOW_USER = '78341716'
# TWEETS_PER_QUERY = 15

TWITTER_CONSUMER_KEY = 'V3ZGJyq2yUAw2XVKiKahhHJTs'
TWITTER_CONSUMER_SECRET = 'GUbRJb2lQNVacjKlYJNERvucKoagt4tZiXRTGVQ5O5ezh9vaSz'
TWITTER_ACCESS_TOKEN = '134934756-fQY6RCs2znO2OrsFQjBfCulWsQpswFxTxDZgpDyW'
TWITTER_TOKEN_SECRET = 'Z1xrn1WaFtTS3TIY6zPqvGbO2zCqJZHNvrJU1zvtNTK7l'

TWITTER_HASH_TAG = '#djangocon'
TWITTER_FOLLOW_USER = '78341716'
TWEETS_PER_QUERY = 15