# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(max_length=300)),
                ('favorite_count', models.IntegerField(default=0)),
                ('id_str', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=300)),
                ('user_description', models.CharField(max_length=300)),
                ('user_followers_count', models.IntegerField(default=0)),
                ('user_id_str', models.CharField(max_length=300)),
                ('user_location', models.CharField(max_length=300)),
                ('user_name', models.CharField(max_length=300)),
                ('user_screen_name', models.CharField(max_length=300)),
                ('user_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
