# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='id_str',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='source',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_id_str',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_screen_name',
            field=models.CharField(max_length=60),
        ),
    ]
