# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20170814_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='id_str',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_id_str',
            field=models.CharField(max_length=100),
        ),
    ]
